name: {{project_name.snakeCase()}}_project
# TODO update repository url to your own
# Needed for generating commit links in package changelogs
#repository: https://github.com/{your_user_name}/{repo_name}.git

packages:
  # Directory where the app will live
  - {{project_name.snakeCase()}}
  - {{project_name.snakeCase()}}/widgetbook

categories:
  app:
    - {{project_name.snakeCase()}}
  widgetbook:
    - {{project_name.snakeCase()}}/widgetbook


command:
  version:
    # Uncomment to generate commit links in package changelogs.
    # linkToCommits: true
    # Uncomment to only allow versioning to happen on main branch.
    # branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
    releaseUrl: true

  bootstrap:
    hooks:
      post: melos build_runner && melos gen_l10n && melos fix
    runPubGetInParallel: true
    usePubspecOverrides: true

    environment:
      sdk: ^3.5.0

scripts:
  build_runner:
    run: melos exec --depends-on="build_runner" dart run build_runner build --delete-conflicting-outputs
    description: Run `build_runner build` in all packages.
  gen_l10n:
    run: melos exec --depends-on="flutter_localizations" flutter gen-l10n
    description: Generate localization files for all packages.
  fix:
    run: melos exec -- dart format . && melos exec -- dart fix --apply
    description: Run `dart format` in all packages.
  test:
    run: melos run test:selective_unit_test --no-select
    description: Run all Flutter tests in this project.
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.
