// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyUrCVrHjS3IUsc_esJTKIix0jMQlSzjE',
    appId: '1:1078268621920:web:f9e7aa72941683f2a53f05',
    messagingSenderId: '1078268621920',
    projectId: 'apostletec-ai-chat-app-dev',
    authDomain: 'apostletec-ai-chat-app-dev.firebaseapp.com',
    storageBucket: 'apostletec-ai-chat-app-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMeD3am5si7haxQC2uDwtXIBLZJg_5CkA',
    appId: '1:1078268621920:android:c032aa24b1dcf339a53f05',
    messagingSenderId: '1078268621920',
    projectId: 'apostletec-ai-chat-app-dev',
    storageBucket: 'apostletec-ai-chat-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnUIKCzLhiBsZ53m6XEHtGcd3FKLNkETQ',
    appId: '1:1078268621920:ios:e940d5760adfa537a53f05',
    messagingSenderId: '1078268621920',
    projectId: 'apostletec-ai-chat-app-dev',
    storageBucket: 'apostletec-ai-chat-app-dev.appspot.com',
    iosBundleId: 'com.apostletec.ai-chat-app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnUIKCzLhiBsZ53m6XEHtGcd3FKLNkETQ',
    appId: '1:1078268621920:ios:e940d5760adfa537a53f05',
    messagingSenderId: '1078268621920',
    projectId: 'apostletec-ai-chat-app-dev',
    storageBucket: 'apostletec-ai-chat-app-dev.appspot.com',
    iosBundleId: 'com.apostletec.ai-chat-app.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyUrCVrHjS3IUsc_esJTKIix0jMQlSzjE',
    appId: '1:1078268621920:web:41d726335226efa4a53f05',
    messagingSenderId: '1078268621920',
    projectId: 'apostletec-ai-chat-app-dev',
    authDomain: 'apostletec-ai-chat-app-dev.firebaseapp.com',
    storageBucket: 'apostletec-ai-chat-app-dev.appspot.com',
  );
}
