name: ai_chat_app
description: ai_chat_app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_serializable: ^6.8.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
